# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import logservice_pb2 as logservice__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in logservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogbookServiceStub(object):
    """The Logbook service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLogsByDateRange = channel.unary_stream(
                '/logbook.LogbookService/GetLogsByDateRange',
                request_serializer=logservice__pb2.LogDateRangeRequest.SerializeToString,
                response_deserializer=logservice__pb2.LogEntriesResponse.FromString,
                _registered_method=True)


class LogbookServiceServicer(object):
    """The Logbook service definition
    """

    def GetLogsByDateRange(self, request, context):
        """RPC method to get logs by date range
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogbookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLogsByDateRange': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLogsByDateRange,
                    request_deserializer=logservice__pb2.LogDateRangeRequest.FromString,
                    response_serializer=logservice__pb2.LogEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logbook.LogbookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logbook.LogbookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogbookService(object):
    """The Logbook service definition
    """

    @staticmethod
    def GetLogsByDateRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/logbook.LogbookService/GetLogsByDateRange',
            logservice__pb2.LogDateRangeRequest.SerializeToString,
            logservice__pb2.LogEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LogListServiceStub(object):
    """The Log List service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLogListByHost = channel.unary_unary(
                '/logbook.LogListService/GetLogListByHost',
                request_serializer=logservice__pb2.LogListRequest.SerializeToString,
                response_deserializer=logservice__pb2.LogListResponse.FromString,
                _registered_method=True)
        self.GetLogHostList = channel.unary_unary(
                '/logbook.LogListService/GetLogHostList',
                request_serializer=logservice__pb2.LogHostListRequest.SerializeToString,
                response_deserializer=logservice__pb2.LogHostListResponse.FromString,
                _registered_method=True)


class LogListServiceServicer(object):
    """The Log List service definition
    """

    def GetLogListByHost(self, request, context):
        """RPC method to get log names by host
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogHostList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogListServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLogListByHost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogListByHost,
                    request_deserializer=logservice__pb2.LogListRequest.FromString,
                    response_serializer=logservice__pb2.LogListResponse.SerializeToString,
            ),
            'GetLogHostList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogHostList,
                    request_deserializer=logservice__pb2.LogHostListRequest.FromString,
                    response_serializer=logservice__pb2.LogHostListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logbook.LogListService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logbook.LogListService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogListService(object):
    """The Log List service definition
    """

    @staticmethod
    def GetLogListByHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logbook.LogListService/GetLogListByHost',
            logservice__pb2.LogListRequest.SerializeToString,
            logservice__pb2.LogListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogHostList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logbook.LogListService/GetLogHostList',
            logservice__pb2.LogHostListRequest.SerializeToString,
            logservice__pb2.LogHostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
